name: Ex2
on: 
  issues:
    types: [opened, edited, closed]
  gollum:
  pull_request:
    types: [ready_for_review]
  schedule:
    - cron : '0 0 1 * *'
jobs:
  runs-on: ubuntu-latest
  steps:
    - run: echo "Hello, world! Today is ";date +"%d-%m-%Y %H-%M-%S"
