name: Exo2
on: 
  issues:
    types: [opened, edited, closed]
  gollum:
  pull_request:
    types: [ready_for_review]
  workflow_dispatch:
  schedule:
    - cron : '0 0 1 * *'
jobs:
  Exo2:
    runs-on: ubuntu-latest
    steps:
      - run: echo -n "Hello, world! Today is ";date +"%d-%m-%Y %H-%M-%S"
