name: Exo5
on: workflow_dispatch
jobs:
  nginx:
    runs-on: ubuntu-latest
    services:
      nginx:
        image: nginx
        ports:
          - 4242:80
    steps:
      - name: request
        run: curl -v http://localhost:4242/
